language: python
python:
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  on:
    tags: true
    # only deploy on python 3.6
    python: 3.6
  provider: pypi
  distributions: sdist bdist_wheel
  user: Joseph.Rawson
  password:
    secure: fslFarIZNN1TTVNN5oEHHnuMnVpmCjsqNrXXcUN7OjyIMhIQelQ+u2/kajpHKi+zpLJHeXt9hnx2b4xfCm9gYigLVjRpzzgN58bCbz7lz8gjzwwddx34TU09AXLXl+Zgj0EwKJmeXZ/dWCGzM7Yux8UMzbDZlmcayGe0/8/jEHo=
