language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  on:
    all_branches: true
    tags: true
  provider: pypi
  distributions: sdist bdist_wheel
  user: Joseph.Rawson
  password:
    secure: fslFarIZNN1TTVNN5oEHHnuMnVpmCjsqNrXXcUN7OjyIMhIQelQ+u2/kajpHKi+zpLJHeXt9hnx2b4xfCm9gYigLVjRpzzgN58bCbz7lz8gjzwwddx34TU09AXLXl+Zgj0EwKJmeXZ/dWCGzM7Yux8UMzbDZlmcayGe0/8/jEHo=
